version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports

  dashboard:
    build: .
    command: streamlit run dashboard/app.py --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./reports:/app/reports
    environment:
      - API_URL=http://api:8000
